name: TRAVIS

on:

  push:

    branches:

      - master

  pull_request:

    brancges:

      - master


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

        with:

          python-version: '3.8'

      - name: Install dependecies

        run:

          pip install flask

      - name: Run tests

        run:

          python flaskapp/some_app.py
